load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "check_authors_test",
    srcs = [
        "check_authors.py",
        "check_authors_test.py",
    ],
    main = "check_authors_test.py",
    python_version = "3.12",
)

py_test(
    name = "check_signatures_test",
    srcs = [
        "check_signatures.py",
        "check_signatures_test.py",
    ],
    main = "check_signatures_test.py",
    python_version = "3.12",
)
