#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""Convert Doxygen XML into a linked, repository-native code reference.

Doxygen's XML preserves semantic relationships that are lost when its HTML is
copied or flattened. This converter uses ``index.xml`` as the canonical symbol
ownership map, emits one Markdown page per compound, and rewrites every known
``refid`` into a relative page-and-anchor link. The result can move as one
directory under ``docs/code`` without breaking cross-references.

The implementation intentionally supports the subset of Doxygen XML used by
the project instead of attempting to become a general documentation theme. It
fails on broken generated links so unsupported markup cannot silently produce
a reference tree that looks complete but is not navigable.
"""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


## Ownership marker placed first in every generated Markdown document.
GENERATED_NOTICE = (
    "<!-- Generated by utils/scripts/update_docs.sh. Do not edit directly. -->"
)

## Compound kinds that produce useful public pages; directory internals are omitted.
COMPOUND_KINDS = {
    "class",
    "concept",
    "file",
    "group",
    "interface",
    "namespace",
    "page",
    "struct",
    "union",
}

## Reader-facing headings for Doxygen's terse section-kind codes.
SECTION_TITLES = {
    "define": "Macros",
    "enum": "Enumerations",
    "friend": "Friends",
    "func": "Functions",
    "public-func": "Public functions",
    "public-static-func": "Public static functions",
    "protected-func": "Protected functions",
    "protected-static-func": "Protected static functions",
    "private-func": "Private functions",
    "private-static-func": "Private static functions",
    "public-attrib": "Public data members",
    "public-static-attrib": "Public static data members",
    "protected-attrib": "Protected data members",
    "protected-static-attrib": "Protected static data members",
    "private-attrib": "Private data members",
    "private-static-attrib": "Private static data members",
    "public-type": "Public types",
    "protected-type": "Protected types",
    "private-type": "Private types",
    "typedef": "Type aliases",
    "var": "Variables",
}

## Elements that must interrupt inline paragraph accumulation in Markdown.
BLOCK_TAGS = {
    "itemizedlist",
    "orderedlist",
    "parameterlist",
    "programlisting",
    "simplesect",
}

## Local-link extractor used after rendering to reject incomplete page graphs.
MARKDOWN_LINK = re.compile(r"\[[^]]*\]\(([^)]+)\)")


@dataclass(frozen=True)
class LinkTarget:
    """Describe the Markdown destination assigned to a Doxygen ``refid``.

    Compound references target a page; member references add an explicit
    anchor. Keeping this mapping independent of rendering lets prose, parameter
    documentation, and related-symbol lists use identical link semantics.

    @param page Markdown filename relative to ``docs/code``.
    @param anchor Optional stable member anchor within that page.
    """

    ## @cond DATACLASS_STORAGE
    # Doxygen's Python parser coalesces annotation-only dataclass fields into a
    # single static member. The class contract above documents these fields;
    # hiding their storage declarations prevents a misleading generated API.
    # Markdown file containing the referenced compound or member.
    page: str

    # Explicit member anchor, or None when the page itself is the target.
    anchor: str | None = None
    ## @endcond


@dataclass(frozen=True)
class Compound:
    """Keep index metadata and parsed detail XML together for one page.

    @param refid Doxygen's stable identifier and detail XML basename.
    @param kind Doxygen compound kind, such as class, namespace, or file.
    @param name Human-readable qualified name shown in the generated index.
    @param page Destination Markdown filename.
    @param element Parsed root of the compound's XML document.
    """

    ## @cond DATACLASS_STORAGE
    # See LinkTarget: the human-readable field contract belongs in the class
    # documentation, while these declarations remain implementation storage.
    # Doxygen identifier used to join index and detail XML.
    refid: str

    # Semantic compound category used to group the generated landing page.
    kind: str

    # Qualified display name preserved from Doxygen's index.
    name: str

    # Stable Markdown filename derived from refid.
    page: str

    # Parsed detail XML retained to avoid reparsing during rendering.
    element: ET.Element
    ## @endcond


def _markdown_escape(text: str) -> str:
    """Protect prose originating in XML from becoming Markdown syntax.

    Formatting introduced deliberately by the renderer is added after this
    escape step, which prevents identifiers containing underscores or brackets
    from changing the structure of the output.

    @param text Plain text extracted from Doxygen XML.
    @return Text safe to embed in a Markdown paragraph or link label.
    """
    return re.sub(r"([\\`*_[\]])", r"\\\1", text)


def _normalize_inline(text: str) -> str:
    """Remove XML pretty-printing whitespace from inline prose.

    Doxygen indents XML for readability, but those newlines are not paragraph
    boundaries. Real block boundaries are handled before this function runs.

    @param text Rendered inline fragment.
    @return Fragment with runs of whitespace collapsed to one space.
    """
    return re.sub(r"\s+", " ", text).strip()


def _plain_text(element: ET.Element | None) -> str:
    """Flatten an XML subtree when markup would be invalid or distracting.

    Signatures and code listings must remain literal code rather than contain
    clickable Markdown. Doxygen represents spaces in highlighted code with
    explicit ``sp`` elements, so those nodes need special handling.

    @param element XML subtree, or ``None`` for an absent optional field.
    @return Concatenated textual content with code spacing preserved.
    """
    if element is None:
        return ""

    pieces = [element.text or ""]
    for child in element:
        if child.tag == "sp":
            pieces.append(" ")
        elif child.tag == "linebreak":
            pieces.append("\n")
        else:
            pieces.append(_plain_text(child))
        pieces.append(child.tail or "")
    return "".join(pieces)


def _anchor(refid: str) -> str:
    """Derive an explicit, GitHub-compatible anchor from a Doxygen ID.

    Explicit anchors avoid relying on renderer-specific heading slug rules and
    keep links stable when a displayed function name is overloaded or renamed.

    @param refid Doxygen symbol identifier.
    @return Sanitized HTML anchor used in generated Markdown.
    """
    return "symbol-" + re.sub(r"[^a-zA-Z0-9_.-]", "-", refid)


class MarkdownRenderer:
    """Render Doxygen description nodes in the context of one output page.

    Doxygen references carry only a ``refid``. The renderer combines the
    repository-wide destination map with the current page so self-links can be
    shortened while cross-page links remain relative and relocatable.
    """

    def __init__(self, targets: dict[str, LinkTarget], current_page: str):
        """Bind symbol destinations to a page-specific rendering context.

        @param targets Canonical mapping from Doxygen IDs to Markdown targets.
        @param current_page Filename currently being generated.
        """
        ## Repository-wide canonical destinations for Doxygen references.
        self.targets = targets

        ## Page being rendered, used to shorten links to local fragments.
        self.current_page = current_page

    def _href(self, target: LinkTarget) -> str:
        """Build the shortest valid relative reference to a known target.

        @param target Page and optional anchor selected for a Doxygen ID.
        @return Same-page fragment or sibling Markdown link.
        """
        page = "" if target.page == self.current_page else target.page
        if target.anchor:
            return f"{page}#{target.anchor}"
        return page or "#"

    def _inline_element(self, element: ET.Element) -> str:
        """Translate one inline Doxygen element without losing child text.

        Unknown tags intentionally degrade to their rendered contents. This
        preserves documentation written with newer Doxygen markup while only
        adding Markdown syntax for constructs whose behavior is understood.

        @param element Inline XML element to translate.
        @return Markdown fragment representing the element.
        """
        tag = element.tag
        content = self._inline_contents(element)

        if tag == "ref":
            target = self.targets.get(element.get("refid", ""))
            return f"[{content}]({self._href(target)})" if target else f"`{content}`"
        if tag == "ulink":
            return f"[{content}]({element.get('url', '')})"
        if tag in {"computeroutput", "verbatim"}:
            return f"`{_plain_text(element).strip()}`"
        if tag == "bold":
            return f"**{content}**"
        if tag == "emphasis":
            return f"*{content}*"
        if tag == "sp":
            return " "
        if tag == "linebreak":
            return "  \n"
        if tag == "ndash":
            return "–"
        if tag == "mdash":
            return "—"
        if tag == "formula":
            formula = _plain_text(element).strip().strip("$")
            return f"${formula}$"
        return content

    def _inline_contents(self, element: ET.Element) -> str:
        """Render mixed XML content, including text following child elements.

        ElementTree stores text after a child in ``child.tail``. Omitting tails
        is a subtle failure mode that joins or drops words around references.

        @param element Parent containing mixed prose and inline elements.
        @return Unnormalized Markdown fragment.
        """
        pieces = [_markdown_escape(element.text or "")]
        for child in element:
            pieces.append(self._inline_element(child))
            pieces.append(_markdown_escape(child.tail or ""))
        return "".join(pieces)

    def inline(self, element: ET.Element | None) -> str:
        """Render an optional inline container and normalize XML indentation.

        @param element Inline XML container, or ``None`` when absent.
        @return One normalized Markdown inline fragment.
        """
        if element is None:
            return ""
        return _normalize_inline(self._inline_contents(element))

    def _program_listing(self, element: ET.Element) -> str:
        """Reconstruct highlighted Doxygen code as an ordinary fenced block.

        Syntax-highlight spans are deliberately flattened: Markdown renderers
        can highlight the resulting fence, while retaining Doxygen's nested
        spans would produce noisy HTML and broken copy/paste behavior.

        @param element ``programlisting`` XML node.
        @return Markdown fenced code block.
        """
        lines = [_plain_text(line).rstrip() for line in element.findall("codeline")]
        language = (
            "cpp"
            if element.get("filename", "").endswith((".c", ".cc", ".cpp", ".h", ".hpp"))
            else ""
        )
        return f"```{language}\n" + "\n".join(lines).rstrip() + "\n```"

    def _parameter_list(self, element: ET.Element) -> str:
        """Render Doxygen's several parameter-list kinds consistently.

        Parameter, exception, return-value, and template-parameter lists share
        one XML shape. A compact Markdown list keeps long API pages scannable
        while preserving direction annotations such as ``in`` and ``out``.

        @param element ``parameterlist`` XML node.
        @return Titled Markdown list.
        """
        kind = element.get("kind", "param")
        title = {
            "exception": "Throws",
            "param": "Parameters",
            "retval": "Return values",
            "templateparam": "Template parameters",
        }.get(kind, kind.replace("_", " ").title())
        lines = [f"**{title}**", ""]
        for item in element.findall("parameteritem"):
            names = []
            for name in item.findall("./parameternamelist/parametername"):
                direction = name.get("direction")
                label = f"`{_plain_text(name).strip()}`"
                if direction:
                    label += f" ({direction})"
                names.append(label)
            description = self.blocks(item.find("parameterdescription"))
            description = description.replace("\n", "\n  ")
            lines.append(f"- {', '.join(names)} — {description}".rstrip())
        return "\n".join(lines)

    def _list(self, element: ET.Element, ordered: bool) -> str:
        """Render nested block content without breaking Markdown indentation.

        @param element Doxygen itemized or ordered list.
        @param ordered Select numeric rather than bullet markers.
        @return Markdown list with continuation lines indented.
        """
        lines = []
        for index, item in enumerate(element.findall("listitem"), start=1):
            prefix = f"{index}." if ordered else "-"
            content = self.blocks(item).replace("\n", "\n  ")
            lines.append(f"{prefix} {content}")
        return "\n".join(lines)

    def _simple_section(self, element: ET.Element) -> str:
        """Turn Doxygen semantic callouts into compact labeled paragraphs.

        @param element ``simplesect`` node such as return, note, or warning.
        @return Markdown paragraph retaining the section's semantic label.
        """
        title = {
            "attention": "Attention",
            "note": "Note",
            "return": "Returns",
            "see": "See also",
            "since": "Since",
            "warning": "Warning",
        }.get(element.get("kind", ""), "Details")
        return f"**{title}:** {self.inline(element)}"

    def _paragraph(self, element: ET.Element) -> str:
        """Split a Doxygen paragraph around embedded block-level constructs.

        Doxygen may place a code listing or parameter list inside ``para``.
        Markdown cannot safely nest those blocks in an inline string, so the
        accumulated inline text is flushed before and after each block node.

        @param element Doxygen ``para`` node.
        @return One or more Markdown paragraphs and blocks.
        """
        result = []
        inline_pieces = [_markdown_escape(element.text or "")]

        def flush_inline() -> None:
            """Commit pending prose only when it contains meaningful text."""
            text = _normalize_inline("".join(inline_pieces))
            if text:
                result.append(text)
            inline_pieces.clear()

        for child in element:
            if child.tag in BLOCK_TAGS:
                flush_inline()
                result.append(self.block(child))
            else:
                inline_pieces.append(self._inline_element(child))
            inline_pieces.append(_markdown_escape(child.tail or ""))
        flush_inline()
        return "\n\n".join(part for part in result if part)

    def block(self, element: ET.Element) -> str:
        """Dispatch a block node to the renderer that understands its shape.

        @param element Doxygen description child.
        @return Markdown representation of that block.
        """
        if element.tag == "para":
            return self._paragraph(element)
        if element.tag == "programlisting":
            return self._program_listing(element)
        if element.tag == "parameterlist":
            return self._parameter_list(element)
        if element.tag == "itemizedlist":
            return self._list(element, ordered=False)
        if element.tag == "orderedlist":
            return self._list(element, ordered=True)
        if element.tag == "simplesect":
            return self._simple_section(element)
        return self.inline(element)

    def blocks(self, element: ET.Element | None) -> str:
        """Render a description container with Markdown paragraph separation.

        @param element Brief, detailed, or parameter description container.
        @return Rendered nonempty children separated by blank lines.
        """
        if element is None:
            return ""
        rendered = [self.block(child) for child in element]
        return "\n\n".join(part for part in rendered if part)


def _description(renderer: MarkdownRenderer, element: ET.Element) -> str:
    """Combine brief and detailed descriptions without inventing content.

    @param renderer Page-aware Markdown renderer.
    @param element Compound, member, or enumeration value containing docs.
    @return Available description sections separated as Markdown paragraphs.
    """
    parts = [
        renderer.blocks(element.find("briefdescription")),
        renderer.blocks(element.find("detaileddescription")),
    ]
    return "\n\n".join(part for part in parts if part)


def _source_link(element: ET.Element) -> str:
    """Link generated API entries back to the checked-in source location.

    Generated pages always live two directories below the repository root, so
    Doxygen's repository-relative paths can remain relative GitHub links. Line
    fragments are included only when Doxygen reports a declaration line.

    @param element XML node that may contain a ``location`` child.
    @return Markdown source link, or an empty string when location is unknown.
    """
    location = element.find("location")
    if location is None or not location.get("file"):
        return ""
    path = location.get("file", "")
    line = location.get("line")
    suffix = f"#L{line}" if line else ""
    return f"[Source](../../{path}{suffix})"


def _signature(member: ET.Element) -> str:
    """Recover a readable declaration from Doxygen's split signature fields.

    Function argument strings are stored separately from definitions. Macros
    have a different XML shape and must be reconstructed from named parameters
    rather than their often multi-line initializer.

    @param member Doxygen ``memberdef`` element.
    @return Plain declaration suitable for a code fence.
    """
    kind = member.get("kind", "")
    name = member.findtext("name", default="")
    definition = _normalize_inline(_plain_text(member.find("definition")))
    args = _normalize_inline(_plain_text(member.find("argsstring")))

    if kind == "define":
        parameters = [
            _plain_text(parameter.find("defname")).strip()
            for parameter in member.findall("param")
        ]
        suffix = f"({', '.join(parameters)})" if parameters else ""
        return f"#define {name}{suffix}"
    return f"{definition}{args}".strip() or name


def _render_member(renderer: MarkdownRenderer, member: ET.Element) -> str:
    """Render one member with an explicit anchor and navigation context.

    Enumeration values receive anchors as well as their parent so references to
    an individual value land at the useful row rather than the top of the page.

    @param renderer Renderer configured for the containing compound page.
    @param member Doxygen member definition.
    @return Complete Markdown section for the member.
    """
    refid = member.get("id", "")
    name = member.findtext("name", default="Unnamed symbol")
    parts = [f'<a id="{_anchor(refid)}"></a>', f"### `{name}`"]
    signature = _signature(member)
    if signature:
        parts.append(f"```cpp\n{signature}\n```")

    description = _description(renderer, member)
    if description:
        parts.append(description)

    enum_values = member.findall("enumvalue")
    if enum_values:
        values = ["#### Values"]
        for value in enum_values:
            value_refid = value.get("id", "")
            value_name = value.findtext("name", default="Unnamed value")
            value_description = _description(renderer, value)
            line = f'- <a id="{_anchor(value_refid)}"></a>`{value_name}`'
            if value_description:
                line += f" — {value_description}"
            values.append(line)
        parts.append("\n".join(values))

    source = _source_link(member)
    if source:
        parts.append(source)
    return "\n\n".join(parts)


def _section_title(kind: str) -> str:
    """Map Doxygen section codes to reader-facing headings with a fallback.

    @param kind Doxygen ``sectiondef`` kind.
    @return Human-readable Markdown heading text.
    """
    return SECTION_TITLES.get(kind, kind.replace("-", " ").capitalize())


def _render_compound(compound: Compound, targets: dict[str, LinkTarget]) -> str:
    """Build one relocatable Markdown page from a Doxygen compound.

    Inner classes and namespaces become a navigation list before member
    sections. All links are resolved through the same target map used by prose,
    preventing the index and body renderers from disagreeing about ownership.

    @param compound Indexed compound and its parsed detail XML.
    @param targets Canonical Doxygen-ID destination map.
    @return Complete generated Markdown document.
    @throws ValueError If the detail XML lacks its required compound definition.
    """
    renderer = MarkdownRenderer(targets, compound.page)
    definition = compound.element.find("compounddef")
    if definition is None:
        raise ValueError(f"missing compounddef in {compound.refid}.xml")

    title_kind = compound.kind.capitalize()
    parts = [GENERATED_NOTICE, f"# {title_kind} `{compound.name}`"]
    description = _description(renderer, definition)
    if description:
        parts.append(description)

    source = _source_link(definition)
    if source:
        parts.append(source)

    related = []
    for tag in ("innerclass", "innernamespace", "innergroup", "innerpage"):
        for item in definition.findall(tag):
            target = targets.get(item.get("refid", ""))
            if target:
                label = _markdown_escape(_plain_text(item).strip())
                related.append(f"- [{label}]({renderer._href(target)})")
    if related:
        parts.append("## Related symbols\n\n" + "\n".join(related))

    for section in definition.findall("sectiondef"):
        members = section.findall("memberdef")
        if not members:
            continue
        rendered = [_render_member(renderer, member) for member in members]
        parts.append(
            f"## {_section_title(section.get('kind', 'symbols'))}\n\n"
            + "\n\n".join(rendered)
        )
    return "\n\n".join(parts).rstrip() + "\n"


def _load_compounds(xml_dir: Path) -> tuple[list[Compound], dict[str, LinkTarget]]:
    """Load documentable compounds and establish canonical symbol ownership.

    ``index.xml`` assigns each member to the page Doxygen considers canonical;
    using that assignment avoids ambiguous links when a function appears in
    both file and namespace XML. Anonymous namespaces are omitted because their
    generated names are unstable and do not form public reference material.
    Empty scopes synthesized by an extension mapping are also omitted; they
    carry no guidance and would otherwise become dead-end index entries.

    @param xml_dir Directory produced by Doxygen's XML generator.
    @return Ordered compounds and the complete reference destination map.
    @throws ValueError If ``index.xml`` is missing.
    @throws xml.etree.ElementTree.ParseError If XML is malformed.
    """
    index_path = xml_dir / "index.xml"
    if not index_path.is_file():
        raise ValueError(f"Doxygen index not found: {index_path}")

    index = ET.parse(index_path).getroot()
    compounds = []
    targets: dict[str, LinkTarget] = {}
    for item in index.findall("compound"):
        refid = item.get("refid", "")
        kind = item.get("kind", "")
        name = item.findtext("name", default="")
        xml_path = xml_dir / f"{refid}.xml"
        if kind not in COMPOUND_KINDS or "@" in name or not xml_path.is_file():
            continue

        element = ET.parse(xml_path).getroot()
        definition = element.find("compounddef")
        if definition is None:
            raise ValueError(f"missing compounddef in {refid}.xml")

        # Extension mappings can make Doxygen synthesize empty language scopes;
        # shell files mapped through the Python parser are one example. A scope
        # is useful only if it explains something, owns a symbol, or leads to a
        # nested symbol. Omitting empty scopes avoids dead-end reference pages.
        descriptions = (
            definition.find("briefdescription"),
            definition.find("detaileddescription"),
        )
        has_description = any(
            description is not None and "".join(description.itertext()).strip()
            for description in descriptions
        )
        has_members = definition.find(".//memberdef") is not None
        has_children = any(
            definition.find(tag) is not None
            for tag in ("innerclass", "innernamespace", "innergroup", "innerpage")
        )
        if not (has_description or has_members or has_children):
            continue

        page = f"{refid}.md"
        compound = Compound(refid, kind, name, page, element)
        compounds.append(compound)
        targets[refid] = LinkTarget(page)
        for member in item.findall("member"):
            member_refid = member.get("refid", "")
            if member_refid:
                targets[member_refid] = LinkTarget(page, _anchor(member_refid))
    return compounds, targets


def _render_index(compounds: list[Compound]) -> str:
    """Create a human-oriented landing page grouped by semantic kind.

    @param compounds Every page emitted by the conversion.
    @return Generated ``README.md`` contents with deterministic ordering.
    """
    by_kind: dict[str, list[Compound]] = {}
    for compound in compounds:
        by_kind.setdefault(compound.kind, []).append(compound)

    parts = [GENERATED_NOTICE, "# puc code reference"]
    for kind in sorted(by_kind):
        title = kind.replace("_", " ").title()
        entries = [
            f"- [`{_markdown_escape(compound.name)}`]({compound.page})"
            for compound in sorted(by_kind[kind], key=lambda item: item.name.casefold())
        ]
        parts.append(f"## {title}\n\n" + "\n".join(entries))
    return "\n\n".join(parts).rstrip() + "\n"


def _validate_links(output_dir: Path) -> None:
    """Fail generation when an internal page or explicit anchor is missing.

    Only Markdown-to-Markdown links are checked here; source and external URLs
    belong to a different tree. Validation happens before installation into
    ``docs/code`` so a failed conversion cannot replace known-good docs.

    @param output_dir Newly rendered staging directory.
    @throws ValueError If a generated local link or anchor is unresolved.
    """
    for page in output_dir.glob("*.md"):
        contents = page.read_text(encoding="utf-8")
        for href in MARKDOWN_LINK.findall(contents):
            path, separator, fragment = href.partition("#")
            if path and not path.endswith(".md"):
                continue
            destination = page if not path else page.parent / path
            if not destination.is_file():
                raise ValueError(f"broken link in {page.name}: {href}")
            if separator and fragment:
                destination_contents = destination.read_text(encoding="utf-8")
                if f'id="{fragment}"' not in destination_contents:
                    raise ValueError(f"broken anchor in {page.name}: {href}")


def convert(xml_dir: Path, output_dir: Path) -> None:
    """Convert one Doxygen XML tree into a validated Markdown directory.

    The destination must not already exist. That contract makes accidental
    partial overwrites impossible and lets ``update_docs.sh`` install the
    completed tree atomically.

    @param xml_dir Doxygen XML directory containing ``index.xml``.
    @param output_dir New directory to create for generated Markdown.
    @throws ValueError If input is incomplete or generated links are broken.
    @throws OSError If input cannot be read or output cannot be created.
    @throws xml.etree.ElementTree.ParseError If Doxygen XML is malformed.
    """

    compounds, targets = _load_compounds(xml_dir)
    if not compounds:
        raise ValueError(f"no documentable compounds found in {xml_dir}")

    output_dir.mkdir(parents=True, exist_ok=False)
    (output_dir / "README.md").write_text(_render_index(compounds), encoding="utf-8")
    for compound in compounds:
        (output_dir / compound.page).write_text(
            _render_compound(compound, targets), encoding="utf-8"
        )
    _validate_links(output_dir)


def _parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse explicit input and output directories for Bazel invocation.

    @param argv Command-line arguments excluding the program name.
    @return Parsed path arguments.
    """
    parser = argparse.ArgumentParser(
        description="Convert Doxygen XML into linked Markdown reference pages."
    )
    parser.add_argument("xml_dir", type=Path, help="Doxygen XML input directory")
    parser.add_argument("output_dir", type=Path, help="new Markdown output directory")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run conversion with concise diagnostics instead of Python tracebacks.

    Tracebacks are useful during development but obscure the actionable cause
    in CI. Expected filesystem, XML, and validation failures therefore share a
    stable one-line diagnostic and nonzero status.

    @param argv Optional arguments for tests; defaults to process arguments.
    @return 0 on success or 1 for an expected conversion failure.
    """
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    try:
        convert(args.xml_dir, args.output_dir)
    except (OSError, ET.ParseError, ValueError) as error:
        print(f"doxygen_xml_to_markdown: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
