/**
 * @file test-app.cpp
 * @brief Interactive visual integration test for the complete TUI rendering
 *        pipeline.
 *
 * This executable is a manual smoke test rather than an automated unit test. It
 * exercises the integration between Screen, Canvas, Layout, ZBuffer, Frame,
 * Theme, terminal resize detection, Unicode rendering, true color, and Canvas
 * frame publication. Run it from a real terminal with:
 *
 *     bazel run //puc-cli/tui:test-app
 *
 * **Expected display**
 *
 * On a terminal large enough for the normal layout, the application should
 * display all of the following on a black background:
 *
 * - One red marker touching each of the four screen corners. Each marker is two
 *   character cells wide and one cell tall, which appears approximately square
 *   with the proportions used by typical terminal fonts.
 * - One white `+` in the center cell of the screen.
 * - A single-line Unicode box touching the top and right screen edges. The box
 *   has a visual width-to-height ratio of 4:3, accounting for the measured
 * pixel dimensions of a terminal cell; it is not expected to contain four
 * columns for every three rows. The top-right red marker is drawn over the box
 * corner to verify Z-ordering.
 * - Three lines inside the box reporting the current terminal width in
 *   characters, height in characters, and sampled frame rate. The frame rate
 *   normally settles near the loop's 60 FPS cap, but its exact value depends on
 *   the terminal and host load.
 *
 * If either terminal dimension is below the minimum required by the layout,
 * the normal display should be cleared and replaced by a centered
 * `Screen too small` message. The message may be clipped when the terminal is
 * narrower than the message itself.
 *
 * **Visual verification**
 *
 * 1. Start with a comfortably large terminal and confirm that all four red
 *    markers touch their respective pairs of edges, the `+` is centered, and
 *    the metrics box is wider than it is tall.
 * 2. Compare the width and height shown in the box with the terminal's reported
 *    row and column counts.
 * 3. Resize the terminal in both directions. The corner markers must remain
 *    anchored, the `+` must move to the new center, the metrics values must
 *    update, and the box must retain a visually 4:3 shape without leaving stale
 *    borders or text behind.
 * 4. Shrink the terminal until `Screen too small` appears. No corner markers,
 *    center glyph, metrics box, or old frame contents should remain. Enlarge
 * the terminal and confirm that the normal layout returns.
 * 5. Press Ctrl-C and verify that the alternate screen is left, the cursor and
 *    terminal input mode are restored, and the shell remains usable.
 *
 * @note A terminal window can contain a thin strip of pixels that is smaller
 * than one character cell, especially along its bottom edge. A cell-based TUI
 * cannot draw into that strip; anchors should be judged against the terminal's
 * addressable character grid.
 */

#include <algorithm>
#include <chrono>
#include <csignal>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iomanip>
#include <memory>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <thread>
#include <utility>
#include <vector>

#include "puc-cli/tui/canvas.hpp"
#include "puc-cli/tui/frame.hpp"
#include "puc-cli/tui/layout.hpp"
#include "puc-cli/tui/screen.hpp"
#include "puc-cli/tui/state.hpp"
#include "puc-cli/tui/status.hpp"
#include "puc-cli/tui/theme.hpp"
#include "utils/logger/logger.hpp"

/** @cond TUI_LOGGER_MODULE */
LOGGER_MODULE("TUI Test App");
/** @endcond */

namespace {

using puc::tui::Canvas;
using puc::tui::CellDimensions;
using puc::tui::Frame;
using puc::tui::Layout;
using puc::tui::Screen;
using puc::tui::State;
using puc::tui::Status;
using puc::tui::Theme;

/** RGB color used by the four corner markers. */
constexpr uint32_t kRed = 0xff0000;
/** Default foreground used by the smoke-test frames. */
constexpr uint32_t kWhite = 0xffffff;
/** Default background used by the smoke-test frames. */
constexpr uint32_t kBlack = 0x000000;
/** Message displayed in place of the layout below its minimum dimensions. */
constexpr std::string_view kScreenTooSmall = "Screen too small";

/** Queue receiving events generated by Screen. */
std::shared_ptr<Screen::EventBuffer> event_buffer;
/** Terminal session owned for the lifetime of the application. */
std::unique_ptr<Screen> screen;
/** Canvas matching the current terminal cell dimensions. */
std::shared_ptr<Canvas> canvas;
/** Declarative description of every smoke-test frame. */
std::shared_ptr<Layout::LayoutDescription> layout_description;
/** Frame rectangles solved for the current screen geometry. */
Layout::AbsoluteLayout absolute_layout;
/** Constraint solver and compositor. */
Layout layout;
/** Per-frame terminal metrics shared with frames. */
State state;
/** Physical proportions reported for the current terminal cells. */
CellDimensions cell_dimensions = puc::tui::kDefaultCellDimensions;
/** Semantic palette used by smoke-test frames. */
Theme theme;

/** Start of the current frame-rate sampling interval. */
std::chrono::steady_clock::time_point frame_rate_sample;
/** Frames drawn since `frame_rate_sample`. */
size_t frames_since_sample = 0;
/** Smallest terminal width that can display the normal layout. */
size_t minimum_screen_width = 0;
/** Smallest terminal height that can display the normal layout. */
size_t minimum_screen_height = 0;
/** Async-signal-safe flag set by the termination handler. */
volatile std::sig_atomic_t stop_requested = 0;
/** Tracks small-screen mode so transitions can be logged once. */
bool showing_screen_too_small = false;

/**
 * Construct a fully specified Canvas cell.
 *
 * @param[in] character Unicode scalar value to display.
 * @param[in] foreground Packed `0xRRGGBB` foreground.
 * @param[in] background Packed `0xRRGGBB` background.
 * @return A cell containing the supplied values.
 */
Canvas::Cell make_cell(char32_t character, uint32_t foreground,
                       uint32_t background) {
  return Canvas::Cell{
      .character        = character,
      .foreground_color = foreground,
      .background_color = background,
  };
}

/**
 * Adapt a vector-of-vectors grid to Canvas's row-span write interface.
 *
 * @param[in,out] target Canvas receiving the cells.
 * @param[in] rect Destination rectangle.
 * @param[in,out] cells Row-major cell grid matching `rect`.
 * @return The result of Canvas::write_cells().
 */
Status write_grid(Canvas& target, const Canvas::Rect& rect,
                  std::vector<std::vector<Canvas::Cell>>& cells) {
  std::vector<std::span<Canvas::Cell>> rows;
  rows.reserve(cells.size());

  for (auto& row : cells) {
    rows.emplace_back(row);
  }

  const std::span<std::span<Canvas::Cell>> cell_span{rows};
  return target.write_cells(rect, cell_span);
}

/** Frame that fills its assigned rectangle with one background color. */
class SolidFrame final : public Frame {
 public:
  /**
   * Construct a solid-color frame.
   *
   * @param[in] name Frame name.
   * @param[in] color Packed RGB value used for foreground and background.
   */
  SolidFrame(std::string name, uint32_t color)
      : Frame(std::move(name)), color_(color) {}

  Status draw(const State&, const Theme&, Canvas& target,
              const Canvas::Rect& rect) override {
    std::vector<std::vector<Canvas::Cell>> cells(
        rect.height,
        std::vector<Canvas::Cell>(rect.width, make_cell(U' ', color_, color_)));
    return write_grid(target, rect, cells);
  }

  bool needs_update() const override { return true; }

 private:
  /** Packed fill color. */
  uint32_t color_;
};

/** Frame that places one glyph at the center of its assigned rectangle. */
class GlyphFrame final : public Frame {
 public:
  /**
   * Construct a centered-glyph frame.
   *
   * @param[in] name Frame name.
   * @param[in] glyph Unicode scalar value placed at the center cell.
   * @param[in] foreground Packed glyph foreground color.
   * @param[in] background Packed rectangle background color.
   */
  GlyphFrame(std::string name, char32_t glyph, uint32_t foreground,
             uint32_t background)
      : Frame(std::move(name)),
        glyph_(glyph),
        foreground_(foreground),
        background_(background) {}

  Status draw(const State&, const Theme&, Canvas& target,
              const Canvas::Rect& rect) override {
    if (rect.width == 0 || rect.height == 0) {
      return Status::OK;
    }

    std::vector<std::vector<Canvas::Cell>> cells(
        rect.height,
        std::vector<Canvas::Cell>(rect.width,
                                  make_cell(U' ', foreground_, background_)));
    cells[rect.height / 2][rect.width / 2] =
        make_cell(glyph_, foreground_, background_);
    return write_grid(target, rect, cells);
  }

  bool needs_update() const override { return true; }

 private:
  /** Glyph placed at the center cell. */
  char32_t glyph_;
  /** Packed glyph foreground color. */
  uint32_t foreground_;
  /** Packed rectangle background color. */
  uint32_t background_;
};

/** Bordered panel showing live terminal dimensions and sampled frame rate. */
class MetricsFrame final : public Frame {
 public:
  /** Construct a named metrics panel. */
  explicit MetricsFrame(std::string name) : Frame(std::move(name)) {}

  Status draw(const State& current_state, const Theme& current_theme,
              Canvas& target, const Canvas::Rect& rect) override {
    if (rect.width == 0 || rect.height == 0) {
      return Status::OK;
    }

    const Theme::Colors colors = current_theme.get_colors();
    std::vector<std::vector<Canvas::Cell>> cells(
        rect.height,
        std::vector<Canvas::Cell>(
            rect.width, make_cell(U' ', colors.text, colors.background)));

    draw_border(cells, colors.text, colors.background);
    write_line(cells, 1,
               "width:  " + format_count(current_state.screen_width) + " chars",
               colors.text, colors.background);
    write_line(
        cells, 2,
        "height: " + format_count(current_state.screen_height) + " chars",
        colors.text, colors.background);
    write_line(cells, 3, format_frame_rate(current_state.frames_per_second),
               colors.text, colors.background);
    return write_grid(target, rect, cells);
  }

  bool needs_update() const override { return true; }

 private:
  /** Format a cell count in the panel's fixed-width numeric column. */
  static std::string format_count(size_t value) {
    std::ostringstream output;
    output << std::setw(4) << value;
    return output.str();
  }

  /** Format the sampled frame rate as a whole-number FPS line. */
  static std::string format_frame_rate(double frames_per_second) {
    std::ostringstream output;
    output << "frame rate: " << std::fixed << std::setprecision(0)
           << std::setw(2) << frames_per_second << " fps";
    return output.str();
  }

  /** Draw a single-line Unicode box around a rectangular cell grid. */
  static void draw_border(std::vector<std::vector<Canvas::Cell>>& cells,
                          uint32_t foreground, uint32_t background) {
    if (cells.size() < 2 || cells.front().size() < 2) {
      return;
    }

    const size_t last_row    = cells.size() - 1;
    const size_t last_column = cells.front().size() - 1;

    for (size_t x = 1; x < last_column; ++x) {
      cells.front()[x] = make_cell(U'─', foreground, background);
      cells.back()[x]  = make_cell(U'─', foreground, background);
    }

    for (size_t y = 1; y < last_row; ++y) {
      cells[y].front() = make_cell(U'│', foreground, background);
      cells[y].back()  = make_cell(U'│', foreground, background);
    }

    cells.front().front() = make_cell(U'┌', foreground, background);
    cells.front().back()  = make_cell(U'┐', foreground, background);
    cells.back().front()  = make_cell(U'└', foreground, background);
    cells.back().back()   = make_cell(U'┘', foreground, background);
  }

  /** Write clipped ASCII text inside the panel's left and right borders. */
  static void write_line(std::vector<std::vector<Canvas::Cell>>& cells,
                         size_t row, std::string_view text, uint32_t foreground,
                         uint32_t background) {
    if (row >= cells.size() || cells[row].size() < 3) {
      return;
    }

    const size_t available = cells[row].size() - 2;
    const size_t count     = std::min(available, text.size());
    for (size_t i = 0; i < count; ++i) {
      cells[row][i + 1] = make_cell(static_cast<unsigned char>(text[i]),
                                    foreground, background);
    }
  }
};

/**
 * Add a frame and all of its constraints to the global test layout.
 *
 * The frame is retained if a later constraint fails, which is acceptable
 * during one-shot setup because the error aborts application initialization.
 *
 * @param[in] frame_id Unique layout id.
 * @param[in] frame Frame implementation for which ownership is shared.
 * @param[in] constraints Constraints applied in the supplied order.
 * @return Status::OK or the first frame/constraint insertion error.
 */
Status add_frame(std::string frame_id, std::shared_ptr<Frame> frame,
                 std::initializer_list<Layout::Constraint> constraints) {
  Status status = layout.add_frame_to_layout_description(
      layout_description, frame_id, std::move(frame));
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  for (const Layout::Constraint& constraint : constraints) {
    status = layout.add_constraint_to_frame(layout_description, frame_id,
                                            constraint);
    if (!puc::tui::is_ok(status)) {
      return status;
    }
  }
  return Status::OK;
}

/**
 * Add one fixed `2 x 1` red marker anchored to a screen corner.
 *
 * @param[in] frame_id Unique marker id.
 * @param[in] horizontal LEFT_ANCHOR or RIGHT_ANCHOR.
 * @param[in] vertical TOP_ANCHOR or BOTTOM_ANCHOR.
 * @return Status::OK or a layout construction error.
 */
Status add_corner(const std::string& frame_id,
                  Layout::ConstraintType horizontal,
                  Layout::ConstraintType vertical) {
  return add_frame(frame_id, std::make_shared<SolidFrame>(frame_id, kRed),
                   {
                       Layout::make_character_constraint(
                           Layout::ConstraintType::MIN_WIDTH, 2),
                       Layout::make_character_constraint(
                           Layout::ConstraintType::MAX_WIDTH, 2),
                       Layout::make_character_constraint(
                           Layout::ConstraintType::MIN_HEIGHT, 1),
                       Layout::make_character_constraint(
                           Layout::ConstraintType::MAX_HEIGHT, 1),
                       Layout::make_character_constraint(horizontal, 0),
                       Layout::make_character_constraint(vertical, 0),
                   });
}

/**
 * Construct the complete smoke-test frame hierarchy and constraints.
 *
 * The metrics panel and center glyph are added before corner markers so the
 * markers remain visible when an extremely small terminal causes overlap.
 *
 * @return Status::OK or the first layout construction error.
 */
Status setup_layout() {
  layout_description = layout.make_layout_description("canvas-test");

  constexpr std::string_view kMetricsFrameId = "metrics";
  Status status =
      add_frame(std::string{kMetricsFrameId},
                std::make_shared<MetricsFrame>(std::string{kMetricsFrameId}),
                {
                    Layout::make_character_constraint(
                        Layout::ConstraintType::MIN_WIDTH, 24),
                    Layout::make_percentage_constraint(
                        Layout::ConstraintType::MAX_WIDTH, 0.40F),
                    Layout::make_ratio_constraint(
                        Layout::ConstraintType::ASPECT_RATIO, 4, 3),
                    Layout::make_character_constraint(
                        Layout::ConstraintType::TOP_ANCHOR, 0),
                    Layout::make_character_constraint(
                        Layout::ConstraintType::RIGHT_ANCHOR, 0),
                });
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  constexpr std::string_view kCenterFrameId = "center";
  status = add_frame(std::string{kCenterFrameId},
                     std::make_shared<GlyphFrame>(std::string{kCenterFrameId},
                                                  U'+', kWhite, kBlack),
                     {
                         Layout::make_character_constraint(
                             Layout::ConstraintType::MIN_WIDTH, 1),
                         Layout::make_character_constraint(
                             Layout::ConstraintType::MAX_WIDTH, 1),
                         Layout::make_character_constraint(
                             Layout::ConstraintType::MIN_HEIGHT, 1),
                         Layout::make_character_constraint(
                             Layout::ConstraintType::MAX_HEIGHT, 1),
                         Layout::make_character_constraint(
                             Layout::ConstraintType::HORIZONTAL_CENTER, 0),
                         Layout::make_character_constraint(
                             Layout::ConstraintType::VERTICAL_CENTER, 0),
                     });
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  // Corner frames are added last so that the ZBuffer draws them over the
  // metrics box when the top-right regions overlap.
  status = add_corner("top-left", Layout::ConstraintType::LEFT_ANCHOR,
                      Layout::ConstraintType::TOP_ANCHOR);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  status = add_corner("top-right", Layout::ConstraintType::RIGHT_ANCHOR,
                      Layout::ConstraintType::TOP_ANCHOR);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  status = add_corner("bottom-left", Layout::ConstraintType::LEFT_ANCHOR,
                      Layout::ConstraintType::BOTTOM_ANCHOR);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  return add_corner("bottom-right", Layout::ConstraintType::RIGHT_ANCHOR,
                    Layout::ConstraintType::BOTTOM_ANCHOR);
}

/**
 * Allocate and attach a Canvas matching new terminal dimensions.
 *
 * The existing global canvas is retained if allocation validation or Screen
 * attachment fails.
 *
 * @param[in] width New terminal columns.
 * @param[in] height New terminal rows.
 * @return Status::OK or the Canvas/Screen error.
 */
Status attach_canvas(size_t width, size_t height) {
  auto next_canvas = std::make_shared<Canvas>(width, height);
  if (!puc::tui::is_ok(next_canvas->get_status())) {
    return next_canvas->get_status();
  }

  const Status status = screen->set_canvas(next_canvas);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  canvas = std::move(next_canvas);
  return Status::OK;
}

/** Update the displayed FPS value at most four times per second. */
void update_frame_rate() {
  ++frames_since_sample;
  const auto now     = std::chrono::steady_clock::now();
  const auto elapsed = now - frame_rate_sample;

  if (elapsed >= std::chrono::milliseconds{250}) {
    state.frames_per_second = static_cast<double>(frames_since_sample) /
                              std::chrono::duration<double>(elapsed).count();
    frames_since_sample = 0;
    frame_rate_sample   = now;
  }
}

/**
 * Request shutdown from a process signal without performing unsafe work.
 *
 * @param[in] signal_number Ignored signal number supplied by `std::signal`.
 */
void request_stop(int signal_number) {
  static_cast<void>(signal_number);
  stop_requested = 1;
}

/**
 * Draw the centered, clipped small-screen message and no normal frames.
 *
 * @return Status::OK for an empty canvas or a successful write, otherwise the
 *         Canvas write error.
 */
Status draw_screen_too_small() {
  const auto [width, height] = canvas->get_dimensions();
  if (width == 0 || height == 0) {
    return Status::OK;
  }

  const Theme::Colors colors   = theme.get_colors();
  const size_t character_count = std::min(width, kScreenTooSmall.size());
  std::vector<std::vector<Canvas::Cell>> cells(
      1, std::vector<Canvas::Cell>(
             character_count,
             make_cell(U' ', colors.text_warning, colors.background)));
  for (size_t index = 0; index < character_count; ++index) {
    cells.front()[index] =
        make_cell(static_cast<unsigned char>(kScreenTooSmall[index]),
                  colors.text_warning, colors.background);
  }

  return write_grid(*canvas,
                    Canvas::Rect{
                        .x      = (width - character_count) / 2,
                        .y      = height / 2,
                        .width  = character_count,
                        .height = 1,
                    },
                    cells);
}

/**
 * Recompute the terminal size required by the normal layout.
 *
 * The message width and one display row are included even if the declarative
 * layout itself would require less space.
 *
 * @return Status::OK or a layout minimum-size error.
 */
Status update_minimum_screen_dimensions() {
  Status status = layout.compute_minimum_dimensions(
      layout_description, cell_dimensions, minimum_screen_width,
      minimum_screen_height);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  minimum_screen_width = std::max(minimum_screen_width, kScreenTooSmall.size());
  minimum_screen_height = std::max(minimum_screen_height, size_t{1});
  Logger<INFO> << "Test app requires at least " << minimum_screen_width << 'x'
               << minimum_screen_height << " terminal cells with "
               << cell_dimensions.width << ':' << cell_dimensions.height
               << " cell dimensions";
  return Status::OK;
}

/**
 * Solve frame rectangles for the currently recorded terminal geometry.
 *
 * @return Status::OK or the first layout validation or resolution error.
 */
Status update_absolute_layout() {
  return layout.compute_absolute_layout(layout_description, state.screen_width,
                                        state.screen_height, cell_dimensions,
                                        absolute_layout);
}

/**
 * Initialize terminal ownership, palette, Canvas, layout, and timing state.
 *
 * @return Status::OK when the draw loop can begin, otherwise the first setup
 *         error. The caller remains responsible for releasing a taken Screen.
 */
Status setup() {
  event_buffer = std::make_shared<Screen::EventBuffer>();

  screen        = std::make_unique<Screen>(event_buffer);
  Status status = screen->take(event_buffer);
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  Theme::Colors colors{};
  colors.primary      = kRed;
  colors.text         = kWhite;
  colors.text_warning = kWhite;
  colors.background   = kBlack;
  theme.load_colors(colors);

  size_t width  = 0;
  size_t height = 0;
  status        = screen->get_dimensions(width, height, cell_dimensions);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  state.screen_width  = width;
  state.screen_height = height;
  status              = attach_canvas(width, height);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  status = setup_layout();
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  status = update_minimum_screen_dimensions();
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  status = update_absolute_layout();
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  frame_rate_sample = std::chrono::steady_clock::now();
  return Status::OK;
}

/**
 * Produce and present one complete application frame.
 *
 * Terminal dimensions and cell proportions are refreshed first. Resize creates
 * a matching Canvas, a cell-proportion change recomputes minimum dimensions,
 * and the selected normal or small-screen composition is then published and
 * presented. A short delay caps the loop near 60 frames per second.
 *
 * @return Status::OK or the first query, layout, Canvas, or Screen error.
 */
Status draw() {
  while (screen->pop_event().has_value()) {
  }

  size_t width  = 0;
  size_t height = 0;
  CellDimensions current_cell_dimensions;
  Status status =
      screen->get_dimensions(width, height, current_cell_dimensions);
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  const bool screen_dimensions_changed =
      width != state.screen_width || height != state.screen_height;
  const bool cell_dimensions_changed =
      current_cell_dimensions != cell_dimensions;
  if (screen_dimensions_changed || cell_dimensions_changed) {
    state.screen_width  = width;
    state.screen_height = height;
    cell_dimensions     = current_cell_dimensions;
    if (screen_dimensions_changed) {
      status = attach_canvas(width, height);
      if (!puc::tui::is_ok(status)) {
        return status;
      }
    }
    status = update_absolute_layout();
    if (!puc::tui::is_ok(status)) {
      return status;
    }
    if (cell_dimensions_changed) {
      status = update_minimum_screen_dimensions();
      if (!puc::tui::is_ok(status)) {
        return status;
      }
    }
  }

  update_frame_rate();
  status = canvas->begin_frame();
  if (!puc::tui::is_ok(status)) {
    return status;
  }

  const Theme::Colors colors = theme.get_colors();
  Status frame_status =
      canvas->clear(make_cell(U' ', colors.text, colors.background));
  const bool screen_too_small =
      width < minimum_screen_width || height < minimum_screen_height;
  if (screen_too_small != showing_screen_too_small) {
    Logger<INFO> << (screen_too_small ? "Showing small-screen message"
                                      : "Restoring test layout");
    showing_screen_too_small = screen_too_small;
  }

  if (puc::tui::is_ok(frame_status)) {
    frame_status = screen_too_small
                       ? draw_screen_too_small()
                       : layout.draw(layout_description, absolute_layout, state,
                                     theme, *canvas);
  }
  const Status end_status = canvas->end_frame();
  if (!puc::tui::is_ok(frame_status)) {
    return frame_status;
  }
  if (!puc::tui::is_ok(end_status)) {
    return end_status;
  }

  status = screen->draw();
  if (!puc::tui::is_ok(status)) {
    return status;
  }
  std::this_thread::sleep_for(std::chrono::milliseconds{16});
  return Status::OK;
}

}  // namespace

/**
 * Run the interactive TUI smoke test until signaled or an operation fails.
 *
 * @return Zero after successful setup, drawing, and terminal restoration;
 *         otherwise one.
 */
int main() {
  const puc::logger::LoggerConf logger_config{
      .global_level = puc::logger::LogLevel::WARN,
  };
  LOGGER_INIT(logger_config);

  if (std::signal(SIGINT, request_stop) == SIG_ERR ||
      std::signal(SIGTERM, request_stop) == SIG_ERR) {
    Logger<ERROR> << "Could not install termination signal handlers";
    return 1;
  }

  Status status = setup();
  if (!puc::tui::is_ok(status)) {
    Logger<ERROR> << "Test app setup failed: "
                  << puc::tui::status_message(status);
    if (screen) {
      static_cast<void>(screen->release());
    }
    return 1;
  }

  while (true) {
    if (stop_requested != 0) {
      break;
    }
    status = draw();
    if (!puc::tui::is_ok(status)) {
      Logger<ERROR> << "Test app draw failed: "
                    << puc::tui::status_message(status);
      break;
    }
  }

  const Status release_status = screen->release();
  return puc::tui::is_ok(status) && puc::tui::is_ok(release_status) ? 0 : 1;
}
